language: r
cache: packages
sudo: required
latex: false

before_install:
  - sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable -y
  - sudo apt-get install golang -y

notifications:
  slack:
    secure: YOxbPBFVAMbDbNc/6tDn5749/qOfJkM+hfTraG9LGstCZC2C4I7rxb3BRkUHphIbFuQiH8BW/L+BKPXkLBL8Hrz4uMMyD3RtMX1A9fZ9WizkHMT4GLCHE011TITiYIeJvv41R7RBuy6rn3RLpID5KeMTTDphIz1TOZdl1zsxqds=
  email:
    on_success: change
    on_failure: change
