language: r
sudo: required
warnings_are_errors: true

before_install:
  - ./build_etcd.sh v2.1.1

r_github_packages:
- jimhester/covr

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  slack:
    secure: YOxbPBFVAMbDbNc/6tDn5749/qOfJkM+hfTraG9LGstCZC2C4I7rxb3BRkUHphIbFuQiH8BW/L+BKPXkLBL8Hrz4uMMyD3RtMX1A9fZ9WizkHMT4GLCHE011TITiYIeJvv41R7RBuy6rn3RLpID5KeMTTDphIz1TOZdl1zsxqds=
  email:
    on_success: change
    on_failure: change
